# Generated by Django 5.2.2 on 2025-06-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lms_cleint', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='materialcompletion',
            index=models.Index(fields=['content_type', 'object_id'], name='lms_cleint__content_3bb97d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcompletion',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='lms_cleint__user_id_a25070_idx'),
        ),
    ]
