# Generated by Django 5.2 on 2025-07-06 08:20

import django.db.models.deletion
import lms_cleint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0002_materialcompletion_lms_cleint__content_3bb97d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms_cleint.teacherprofile'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='file',
            field=models.FileField(upload_to=lms_cleint.models.FileAnswer.get_upload_path),
        ),
    ]
