# Generated by Django 5.2 on 2025-08-02 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0003_fileanswer_graded_at_fileanswer_graded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to='lms_cleint.teacherprofile'),
        ),
    ]
