# Generated by Django 5.2 on 2025-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
