# Generated by Django 5.2 on 2025-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0004_teacherprofile_avatar_alter_fileanswer_graded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars_pre/'),
        ),
    ]
