# Generated by Django 5.2 on 2025-05-22 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0005_question_answer_test_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_check_enabled',
            field=models.BooleanField(default=True, help_text='Использовать AI для проверки текстовых ответов'),
        ),
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.IntegerField(default=70, help_text='Минимальный процент для зачета'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('max_score', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_cleint.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
