# Generated by Django 5.2 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0008_studentprofile_avatar_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
