# Generated by Django 5.2.2 on 2025-06-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0009_article_completed_chapterfile_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='completed',
            new_name='allow_response',
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='allow_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='response_files/'),
        ),
        migrations.AddField(
            model_name='video',
            name='response_file',
            field=models.FileField(blank=True, null=True, upload_to='response_files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_cleint.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
