# Generated by Django 5.2.2 on 2025-06-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0010_rename_completed_video_allow_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='allow_response',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='chapterfile',
            name='allow_response',
        ),
        migrations.RemoveField(
            model_name='chapterfile',
            name='response_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='response_file',
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lms_cleint.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
