# Generated by Django 5.2.2 on 2025-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0011_rename_allow_response_video_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterfile',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_answers/'),
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='answer_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapterfile',
            name='requires_answer',
            field=models.BooleanField(default=False, verbose_name='Требует ответа'),
        ),
    ]
