# Generated by Django 5.2.2 on 2025-06-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0012_chapterfile_answer_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterfile',
            name='answer_file',
        ),
        migrations.RemoveField(
            model_name='chapterfile',
            name='answer_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='chapterfile',
            name='requires_answer',
        ),
    ]
