# Generated by Django 5.2.2 on 2025-06-08 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0013_remove_chapterfile_answer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterfile',
            name='provide_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_answers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chapter_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms_cleint.chapterfile')),
            ],
        ),
    ]
