# Generated by Django 5.2.2 on 2025-06-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_cleint', '0014_chapterfile_provide_answer_fileanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileanswer',
            name='chapter_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_answers', to='lms_cleint.chapterfile'),
        ),
    ]
