# Generated by Django 5.2 on 2025-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='grading_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
